export const validPersonData = {
  dni: 'cedulaDeIdentidad',
  birthday: new Date('2023-12-05T03:00:00.000Z'),
  countyPD: 'MALDONADO',
  address: 'Calle 30 Las Focas, Edificio Santos Dumont, Apartamento 721',
  cp: '20000',
  phone: '095039606',
  email: 'helloramagago@gmail.com',
  dniNumber: '44944137',
  gender: 'masculino',
  cityPD: 'PUNTA DEL ESTE',
  about: 'Soy programador',
  references: [
    {
      referenceType: 'personal',
      referenceName: 'Florencia',
      referenceSurname: 'Gago',
      referencePhone: '095039606',
      referenceCompany: 'Oracle',
      referenceRole: 'Ventas',
    },
  ],
  studies: [
    {
      level: 'gradoTerciario',
      title: 'Licenciado en Ingeniería Audiovisual',
      institute: 'Universidad la Católica',
      fieldOfStudy: 'Audiovisual',
      startStudyDate: new Date('2010-03-01T02:00:00.000Z'),
      currentlyStudying: false,
      endStudyDate: new Date('2014-12-28T02:00:00.000Z'),
      countyStudy: 'MONTEVIDEO',
      cityStudy: 'MONTEVIDEO',
    },
    {
      level: 'postGrado',
      title: 'Programación',
      institute: 'HackAcademy',
      fieldOfStudy: 'Software',
      startStudyDate: new Date('2023-02-07T03:00:00.000Z'),
      endStudyDate: new Date('2023-05-12T03:00:00.000Z'),
      countyStudy: 'MONTEVIDEO',
      cityStudy: 'MONTEVIDEO',
    },
  ],
  workExperiences: [
    {
      role: 'Creador de Contenido',
      company: 'Studios Roff',
      workField: 'backend',
      positionLevel: 'gerente',
      peopleInCharge: '25',
      task: 'Crear videos asombrosos',
      salary: '50000',
      startWorkDate: new Date('2016-08-01T03:00:00.000Z'),
      endWorkDate: new Date('2017-08-01T03:00:00.000Z'),
      skills: ['Javascript', '.Net', 'C#'],
    },
    {
      role: 'Fotógrafo',
      company: 'The End ',
      workField: 'frontend',
      positionLevel: 'Dueño',
      peopleInCharge: '1',
      task: 'Encargado de hacer todo, desde la venta, la realización y mantención de clientes.',
      salary: '50000',
      startWorkDate: new Date('2024-01-01T03:00:00.000Z'),
      currentlyWorking: true,
      endWorkDate: new Date('2024-01-01T03:00:00.000Z'),
      skills: ['.Net', 'PHP', 'AWS'],
    },
  ],
  languages: [
    {
      spokenLevel: 100,
      languageName: 'english',
      readLevel: 100,
      writtenLevel: 100,
    },
    {
      languageName: 'italian',
      spokenLevel: 0,
      readLevel: 0,
      writtenLevel: 0,
    },
  ],
};

export const incompletePersonData = {
  dni: 'cedulaDeIdentidad',
  birthday: new Date('2023-12-05T03:00:00.000Z'),
  countyPD: 'MALDONADO',
  name: 'Lucas',
  surname: 'Gago',
  address: 'Calle 30 Las Focas, Edificio Santos Dumont, Apartamento 721',
  cp: '20000',
  phone: '095039606',
  email: 'helloramagago@gmail.com',
  dniNumber: '44944137',
  gender: 'masculino',
  cityPD: 'PUNTA DEL ESTE',
  about: 'Soy programador',
  references: [
    {
      referenceType: 'personal',
      referenceName: 'Florencia',
      referenceSurname: 'Gago',
      referencePhone: '095039606',
      referenceCompany: 'Oracle',
      referenceRole: 'Ventas',
    },
  ],
  studies: [
    {
      level: 'gradoTerciario',
      title: 'Licenciado en Ingeniería Audiovisual',
      institute: 'Universidad la Católica',
      fieldOfStudy: 'Audiovisual',
      startStudyDate: new Date('2010-03-01T02:00:00.000Z'),
      currentlyStudying: false,
      endStudyDate: new Date('2014-12-28T02:00:00.000Z'),
      countyStudy: 'MONTEVIDEO',
      cityStudy: 'MONTEVIDEO',
    },
    {
      level: 'postGrado',
      title: 'Programación',
      institute: 'HackAcademy',
      fieldOfStudy: 'Software',
      startStudyDate: new Date('2023-02-07T03:00:00.000Z'),
      endStudyDate: new Date('2023-05-12T03:00:00.000Z'),
      countyStudy: 'MONTEVIDEO',
      cityStudy: 'MONTEVIDEO',
    },
  ],
  workExperiences: [
    {
      role: 'Creador de Contenido',
      company: 'Studios Roff',
      workField: 'backend',
      positionLevel: 'gerente',
      peopleInCharge: '25',
      task: 'Crear videos asombrosos',
      salary: '50000',
      startWorkDate: new Date('2016-08-01T03:00:00.000Z'),
      endWorkDate: new Date('2017-08-01T03:00:00.000Z'),
      skills: ['Javascript', '.Net', 'C#'],
    },
    {
      role: 'Fotógrafo',
      company: 'The End ',
      workField: 'frontend',
      positionLevel: 'Dueño',
      peopleInCharge: '1',
      task: 'Encargado de hacer todo, desde la venta, la realización y mantención de clientes.',
      salary: '50000',
      startWorkDate: new Date('2024-01-01T03:00:00.000Z'),
      currentlyWorking: true,
      endWorkDate: new Date('2024-01-01T03:00:00.000Z'),
      skills: ['.Net', 'PHP', 'AWS'],
    },
  ],
  languages: [
    {
      spokenLevel: 100,
      languageName: 'english',
      readLevel: 100,
      writtenLevel: 100,
    },
    {
      languageName: 'italian',
      spokenLevel: 0,
      readLevel: 0,
      writtenLevel: 0,
    },
  ],
};
